# Generated by Django 5.2.5 on 2025-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('radius_m', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
