# Generated by Django 5.2.6 on 2025-09-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequest',
            name='buyer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='user_app.buyerprofile'),
        ),
        migrations.AddField(
            model_name='stall',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='stalls', to='store_app.allergen'),
        ),
        migrations.AddField(
            model_name='stall',
            name='owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='user_app.sellerprofile'),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='store_app.stall'),
        ),
        migrations.AddField(
            model_name='stallimage',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_app.stall'),
        ),
        migrations.AddField(
            model_name='stall',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stalls', to='store_app.tag'),
        ),
        migrations.AddIndex(
            model_name='stallimage',
            index=models.Index(fields=['stall', 'position'], name='store_app_s_stall_i_f7a5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='stallimage',
            index=models.Index(fields=['stall', 'is_primary'], name='store_app_s_stall_i_021f35_idx'),
        ),
    ]
