# Generated by Django 5.2.5 on 2025-09-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_stall_rich_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_app.stall')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['stall', 'position'], name='store_app_s_stall_i_f7a5a7_idx'), models.Index(fields=['stall', 'is_primary'], name='store_app_s_stall_i_021f35_idx')],
            },
        ),
    ]
