# Generated by Django 5.1.1 on 2025-09-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='protein_g',
            field=models.FloatField(default=0),
        ),
    ]
