# Generated by Django 5.2.5 on 2025-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_stallimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='image_url',
        ),
        migrations.AddField(
            model_name='stall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stalls/'),
        ),
    ]
