# Generated by manual edit to switch URL fields to ImageFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_stallimage"),
    ]

    operations = [
        # Only add StallImage.image here; Stall.image is added by sibling 0004 migration.
        migrations.AddField(
            model_name="stallimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stalls/images/"),
        ),
    ]
