# Generated by Django 5.2.5 on 2025-09-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_images_to_file_uploads'),
        ('store_app', '0004_remove_stall_image_url_stall_image'),
    ]

    operations = [
    ]
