# Generated by Django 5.2.5 on 2025-09-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_remove_stall_image_url_stall_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='image',
            new_name='image_url',
        ),
    ]
