# Generated by Django 5.2.5 on 2025-09-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_merge_20250903_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallimage',
            name='href',
        ),
    ]
