# Generated by Django 5.2.5 on 2025-08-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
