# Generated by Django 5.2.5 on 2025-08-26 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_buyerprofile_address_sellerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
