# Generated by Django 5.2.5 on 2025-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_buyerprofile_zipcode_sellerprofile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='avatar',
            field=models.CharField(blank=True, default='chef1', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='avatar',
            field=models.CharField(blank=True, default='chef1', max_length=255),
        ),
    ]
