# Generated by Django 5.2.5 on 2025-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_buyerprofile_avatar_sellerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
