# Generated by manual edit to replace image_url with ImageField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_sellerprofile_image_url"),
    ]

    operations = [
        # Add new image file field; keep legacy image_url for now.
        migrations.AddField(
            model_name="sellerprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/sellers/"),
        ),
    ]
