# Generated by Django 5.2.5 on 2025-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_sellerprofile_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
